# Generated by Django 5.1.1 on 2024-10-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='gravedad',
            field=models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=1),
        ),
        migrations.AddField(
            model_name='reporte',
            name='urgencia',
            field=models.IntegerField(choices=[(1, 'No urgente'), (2, 'Urgente'), (3, 'Critica')], default=1),
        ),
    ]
