# Generated by Django 5.1.1 on 2024-10-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0003_reporte_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='pin_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
