# Generated by Django 5.1.1 on 2024-11-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0004_reporte_pin_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
