# Generated by Django 5.1.1 on 2024-11-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0005_reporte_x_reporte_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='piso',
            field=models.IntegerField(default=-1),
        ),
    ]
