# Generated by Django 5.1.1 on 2024-11-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0006_reporte_piso'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
